# Generated by Django 4.1.4 on 2022-12-10 14:18

import core.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='cvc',
            field=models.IntegerField(validators=[core.models.validate_cvc]),
        ),
        migrations.AlterField(
            model_name='card',
            name='date_start',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='date_stop',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 10, 14, 18, 26, 471244, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='card',
            name='number_cart',
            field=models.CharField(db_index=True, max_length=19, unique=True, validators=[core.models.validate_number]),
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('price', models.IntegerField(validators=[core.models.validate_price])),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.card')),
            ],
        ),
    ]
