# Generated by Django 4.1.4 on 2022-12-10 15:01

import core.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_card_cvc_alter_card_date_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='statuc',
            field=models.CharField(default='SUCCESS', max_length=14),
        ),
        migrations.AlterField(
            model_name='card',
            name='amount_cash',
            field=models.IntegerField(validators=[core.models.validate_price]),
        ),
        migrations.AlterField(
            model_name='card',
            name='date_stop',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 10, 15, 1, 51, 256236, tzinfo=datetime.timezone.utc)),
        ),
    ]
